services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=eposku_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - '3306:3306'
    networks:
      - eposku_network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address :9001
    networks:
      - eposku_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: eposku-server:prod
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - minio
    networks:
      - eposku_network

volumes:
  minio_data:
    driver: local
  mysql_data:
    driver: local

networks:
  eposku_network:
    driver: bridge